### PR TITLE
Refactor cpp-console client to have simple API

### PR DESCRIPTION
**Pull request by qfweiwei**
## Purpose

1. Clean code to make curly brackets on a new line, etc.
2. Refactor C++ client to have simple API by updating mainAudio.cpp, and adding helper.h, DialogConnector.h, helper.cpp, DialogConnector.cpp etc.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
*  Verify the functionalities do not change

### CODE REVIEW

**Comment by dargilco** [comment]
Regarding class name "DialogConnector"

I was looking at files names in the other samples…

In the UWP sample we have files:
DirectLineSpeechDialogBackend.cs (sounds like a bad name)  - Handles connection to DLS
DialogManager.cs - Takes in a new DirectLineSpeechDialogBackend object. Exposes DLS events and dialog states, manages audio output.

In the Windows Voice Assistant client the dialog is managed in the MainWindows.xaml.cs file. We may want to do similar API refactoring there.

So perhaps in the C++ code we can also call it DialogManager, since it does more than just connec to DLS. It also manages TTS playback and exposes states.

**Comment by chschrae** [comment]
Let's be specific about the helper file and rename it to Log.h or Logging.h Also no need for the helper.cpp for just a small function. TECHNICALLY it's better to put all the functions in the cpp so it's only included once in compiling, but since these are small, I'm not worried about it.

**Comment by qfweiwei** [comment]
If we do not have other commonly used functions and enum classes put into helper.h&cpp, we can rename it to Log for more specific.

If we put both log declaration and definition in Log.h and include Log.h in multiple places, we will get error during linkage. To avoid such error, we can either put log definition in a separate Log.cpp file or declare log inline.

**Comment by chschrae** [comment]
#pragma once can be used to avoid the multiple inclusions. Best practices are to have all functions in the cpp.

**Comment by qfweiwei** [comment]
I moved definition from helper.cpp to helper.h, and put #pragma once at the top of helper.h. Still, the build ended up with same errors:
Error LNK2005 "void __cdecl log(void)" (?log@@YAXXZ) already defined in DialogConnector.obj	cppSample mainAudio.obj
Error LNK1169 one or more multiply defined symbols found cppSample cppSample.exe

If I declare log as inline, the errors are gone.

**Comment by dargilco** [comment]
The #pragma once makes sure when you compile a single .cpp file, you don't include the same header twice. So it prevents the compile error. But it does not prevent the linker error, when you are trying to combine several object files into one executable, if more than one object file has this log defined. Make sure the log header is included only in one .cpp file, and declare the function prototype as external in other .cpp files that need to use it.

**Comment by qfweiwei** [comment]
Thanks Darren. Your explanation really gets to the point.

Another option is, if I declare log as a static function, the linker error is gone. Do you like this idea?

**Comment by dargilco** [comment]
Static is fine for now, since the function is mall. Let's move on!

**Comment by qfweiwei** [comment]
Done second commit with 2 changes:
1. Move log function body to log.h, make it a static function, and remove helper.cpp.
2. Rename DialogConnector to DialogManager, both class name and file names.

**Comment by qfweiwei** [comment]
Thanks. Since this is a draft PR, I will close this one and create another PR to merge the changes.

**Pull request merged**
